[BitTorrent]
Session\DefaultSavePath=/data/torrents/
Session\TempPath=/data/torrents/incomplete/

[Preferences]
WebUI\Enabled=true
WebUI\Username=qbittorrent-user
# PBKDF2 for password "adminadmin"
WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
Downloads\SavePath=/data/torrents/
Downloads\TempPath=/data/torrents/incomplete/
